### ISSUE TITLE
Freeze when loading images from OSM Weekly

### ISSUE THREAD

**Issue by Karry** [poetaster/tidings#108]
Hi. When I open article from this rss feed: https://www.weeklyosm.eu/cz/feed and load article images, Tidings freeze completely.

**Comment by Karry** [comment]
Well, it doesn't freeze forever, but for very long time - 20 seconds. From the stacktrace during that freeze, it seems to me that it is not caused by the tidings itself...

```
(gdb) bt
#0  0x0000007fbf4d6d38 in QImage::rgbSwapped_helper (this=0x7fffffddd0) at image/qimage.cpp:3218
#1  0x0000007fb7853a8c in CustomContext::HybrisTextureFactory::image() const () from /usr/lib64/qt5/plugins/scenegraph/libcustomcontext.so
#2  0x0000007fbf9dd7bc in QQuickPixmap::image (this=<optimized out>) at util/qquickpixmapcache.cpp:1321
#3  0x0000007fbfac632c in QQuickTextDocumentWithImageResources::loadResource (this=0x5555cc9040, type=<optimized out>, name=...) at items/qquicktextdocument.cpp:114
#4  0x0000007fbf58cc60 in QTextDocument::resource (this=this@entry=0x5555cc9040, type=type@entry=2, name=...) at text/qtextdocument.cpp:2075
#5  0x0000007fbfac5720 in QQuickTextDocumentWithImageResources::intrinsicSize (format=..., this=0x5555cc9040) at /usr/include/qt5/QtGui/qtextformat.h:733
#6  QQuickTextDocumentWithImageResources::intrinsicSize (this=0x5555cc9040, format=...) at items/qquicktextdocument.cpp:129
#7  0x0000007fbf5ada64 in QTextDocumentLayout::resizeInlineObject (this=this@entry=0x5555e8adf0, item=..., posInDocument=posInDocument@entry=7326, format=...) at text/qtextdocumentlayout.cpp:3044
#8  0x0000007fbf563748 in QTextEngine::shape (this=this@entry=0x55560e6dd0, item=item@entry=11) at ../../include/QtCore/../../src/corelib/tools/qarraydata.h:202
#9  0x0000007fbf575c18 in QTextLine::layout_helper (this=0x7fffffe640, maxGlyphs=<optimized out>) at text/qtextlayout.cpp:1820
#10 0x0000007fbf57556c in QTextLine::layout_helper (this=this@entry=0x7fffffe640, maxGlyphs=maxGlyphs@entry=2147483647) at text/qtextlayout.cpp:2059
#11 0x0000007fbf576754 in QTextLine::setLineWidth (this=0x7fffffe640, width=<optimized out>) at text/qtextlayout.cpp:1585
#12 0x0000007fbf5b0304 in QTextDocumentLayoutPrivate::layoutBlock (this=this@entry=0x5555ec6520, bl=..., blockPosition=blockPosition@entry=7276, blockFormat=..., layoutStruct=layoutStruct@entry=0x7fffffe990, layoutFrom=layoutFrom@entry=7276, 
    layoutTo=layoutTo@entry=2147483647, previousBlockFormat=previousBlockFormat@entry=0x7fffffe770) at ../../include/QtGui/5.6.3/QtGui/private/../../../../../src/gui/painting/qfixed_p.h:86
#13 0x0000007fbf5b46ac in QTextDocumentLayoutPrivate::layoutFlow (this=this@entry=0x5555ec6520, it=..., layoutStruct=layoutStruct@entry=0x7fffffe990, layoutFrom=layoutFrom@entry=7276, layoutTo=layoutTo@entry=2147483647, width=..., width@entry=...)
    at text/qtextdocumentlayout.cpp:2456
#14 0x0000007fbf5b3c68 in QTextDocumentLayoutPrivate::layoutFrame (this=this@entry=0x5555ec6520, f=f@entry=0x5555f4ebc0, layoutFrom=layoutFrom@entry=7276, layoutTo=layoutTo@entry=2147483647, frameWidth=..., frameWidth@entry=..., frameHeight=..., 
    parentY=..., parentY@entry=...) at ../../include/QtGui/5.6.3/QtGui/private/../../../../../src/gui/painting/qfixed_p.h:59
#15 0x0000007fbf5b3fb0 in QTextDocumentLayoutPrivate::layoutFrame (this=this@entry=0x5555ec6520, f=f@entry=0x5555f4ebc0, layoutFrom=layoutFrom@entry=7276, layoutTo=layoutTo@entry=2147483647, parentY=parentY@entry=...) at text/qtextdocumentlayout.cpp:2086
#16 0x0000007fbf5b5e6c in QTextDocumentLayout::doLayout (this=0x5555e8adf0, from=7276, oldLength=oldLength@entry=0, length=2147476371) at ../../include/QtGui/5.6.3/QtGui/private/../../../../../src/gui/painting/qfixed_p.h:59
#17 0x0000007fbf5b64f8 in QTextDocumentLayoutPrivate::ensureLayoutedByPosition (position=<optimized out>, this=<optimized out>) at text/qtextdocumentlayout.cpp:3170
#18 QTextDocumentLayoutPrivate::ensureLayoutedByPosition (position=2147483647, this=0x5555ec6520) at text/qtextdocumentlayout.cpp:3162
#19 QTextDocumentLayoutPrivate::ensureLayoutFinished (this=0x5555ec6520) at text/qtextdocumentlayout.cpp:519
#20 QTextDocumentLayout::documentSize (this=0x5555e8adf0) at text/qtextdocumentlayout.cpp:3142
#21 0x0000007fbfaa8944 in QQuickTextPrivate::updateSize (this=this@entry=0x5555de2720) at ../../include/QtQml/5.6.3/QtQml/private/../../../../../src/qml/qml/ftw/qflagpointer_p.h:217
#22 0x0000007fbfaa977c in QQuickTextPrivate::updateLayout (this=0x5555de2720) at items/qquicktext.cpp:291
#23 0x0000007fbfaa9ae8 in QQuickText::q_updateLayout (this=this@entry=0x5555cd25f0) at items/qquicktext.cpp:230
#24 0x0000007fbfb924a8 in QQuickText::qt_static_metacall (_o=_o@entry=0x5555cd25f0, _c=_c@entry=QMetaObject::InvokeMetaMethod, _id=_id@entry=31, _a=_a@entry=0x7fffffefe0) at .moc/moc_qquicktext_p.cpp:532
#25 0x0000007fbfb92fb4 in QQuickText::qt_metacall (this=0x5555cd25f0, _c=QMetaObject::InvokeMetaMethod, _id=31, _a=0x7fffffefe0) at .moc/moc_qquicktext_p.cpp:887
#26 0x0000007fb40e0f88 in ?? () from /usr/lib64/libsailfishsilica.so.1
#27 0x0000007fbf106e54 in QQmlVMEMetaObject::metaCall (this=0x5555ea6700, o=<optimized out>, c=QMetaObject::InvokeMetaMethod, _id=77, a=0x7fffffefe0) at qml/qqmlvmemetaobject.cpp:876
#28 0x0000007fbf106e24 in QQmlVMEMetaObject::metaCall (this=0x5555ea44b0, o=<optimized out>, c=QMetaObject::InvokeMetaMethod, _id=77, a=0x7fffffefe0) at ../../include/QtQml/5.6.3/QtQml/private/../../../../../src/qml/qml/ftw/qflagpointer_p.h:323
#29 0x0000007fbeb0f188 in QMetaObject::activate (sender=0x5555cc9040, signalOffset=<optimized out>, local_signal_index=<optimized out>, argv=<optimized out>) at kernel/qobject.cpp:3745
#30 0x0000007fbeb0fc6c in QObject::event (this=0x5555cc9040, e=<optimized out>) at kernel/qobject.cpp:1256
#31 0x0000007fbeae5144 in doNotify (event=<optimized out>, receiver=<optimized out>) at ../../include/QtCore/../../src/corelib/kernel/qobject.h:137
#32 QCoreApplication::notify (this=<optimized out>, receiver=<optimized out>, event=<optimized out>) at kernel/qcoreapplication.cpp:1076
#33 0x0000007fbeae52e8 in QCoreApplication::notifyInternal2 (receiver=receiver@entry=0x5555cc9040, event=event@entry=0x7f80296930) at ../../include/QtCore/../../src/corelib/kernel/qobject.h:137
#34 0x0000007fbeae76b8 in QCoreApplication::sendEvent (event=0x7f80296930, receiver=0x5555cc9040) at kernel/qcoreapplication.h:225
#35 QCoreApplicationPrivate::sendPostedEvents (receiver=receiver@entry=0x0, event_type=event_type@entry=0, data=0x55555f1060) at kernel/qcoreapplication.cpp:1650
#36 0x0000007fbeae7bdc in QCoreApplication::sendPostedEvents (receiver=receiver@entry=0x0, event_type=event_type@entry=0) at kernel/qcoreapplication.cpp:1508
#37 0x0000007fbeb37648 in postEventSourceDispatch (s=0x555560ac40) at kernel/qeventdispatcher_glib.cpp:275
#38 0x0000007fbd968d34 in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0
#39 0x0000007fbd968fa0 in ?? () from /usr/lib64/libglib-2.0.so.0
#40 0x0000007fbd969034 in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#41 0x0000007fbeb37a90 in QEventDispatcherGlib::processEvents (this=0x5555609fa0, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#42 0x0000007fbeae3608 in QEventLoop::exec (this=this@entry=0x7ffffff490, flags=..., flags@entry=...) at ../../include/QtCore/../../src/corelib/global/qflags.h:131
#43 0x0000007fbeaeb1d4 in QCoreApplication::exec () at ../../include/QtCore/../../src/corelib/global/qflags.h:111
#44 0x0000005555561f64 in main (argc=<optimized out>, argv=<optimized out>) at src/harbour-tidings.cpp:149
```
